### ISSUE TITLE
Issues are not clear enough

### ISSUE THREAD

**Issue by arturocs** [pepitoenpeligro/cloudbanking#56]
**Is your feature request related to a problem? Please describe.**
Most issues that are not user stories do not even have a description.

**Describe the solution you'd like**
Add some context to the description of each issue.

**Describe alternatives you've considered**
Maybe add some context in the comments

**Additional context**
It is difficult for an outsider who wants to fix one of the issues to know what it is about.

**Comment by pepitoenpeligro** [comment]
@all-contributors please add @arturocs  for tests and code
